      SUBROUTINE SMATRIX_PROD(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.9.21, 2024-09-26
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: g g > t t~ t t~ WEIGHTED<=4 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=64)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
      REAL*8 T
      REAL*8 MATRIX_PROD
      INTEGER IHEL,IDEN, I
      INTEGER JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./
      DATA (NHEL(I,   1),I=1,6) /-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,   2),I=1,6) /-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,   3),I=1,6) /-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,   4),I=1,6) /-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,   5),I=1,6) /-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,   6),I=1,6) /-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,   7),I=1,6) /-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,   8),I=1,6) /-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,   9),I=1,6) /-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  10),I=1,6) /-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  11),I=1,6) /-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  12),I=1,6) /-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  13),I=1,6) /-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  14),I=1,6) /-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  15),I=1,6) /-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  16),I=1,6) /-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  17),I=1,6) /-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  18),I=1,6) /-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  19),I=1,6) /-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  20),I=1,6) /-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  21),I=1,6) /-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  22),I=1,6) /-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  23),I=1,6) /-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  24),I=1,6) /-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  25),I=1,6) /-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  26),I=1,6) /-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  27),I=1,6) /-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  28),I=1,6) /-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  29),I=1,6) /-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  30),I=1,6) /-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  31),I=1,6) /-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  32),I=1,6) /-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  33),I=1,6) / 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  34),I=1,6) / 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  35),I=1,6) / 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  36),I=1,6) / 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  37),I=1,6) / 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  38),I=1,6) / 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  39),I=1,6) / 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  40),I=1,6) / 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  41),I=1,6) / 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  42),I=1,6) / 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  43),I=1,6) / 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  44),I=1,6) / 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  45),I=1,6) / 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  46),I=1,6) / 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  47),I=1,6) / 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  48),I=1,6) / 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  49),I=1,6) / 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  50),I=1,6) / 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  51),I=1,6) / 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  52),I=1,6) / 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  53),I=1,6) / 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  54),I=1,6) / 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  55),I=1,6) / 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  56),I=1,6) / 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  57),I=1,6) / 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  58),I=1,6) / 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  59),I=1,6) / 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  60),I=1,6) / 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  61),I=1,6) / 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  62),I=1,6) / 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  63),I=1,6) / 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  64),I=1,6) / 1, 1, 1,-1, 1,-1/
      DATA IDEN/1024/
C     ----------
C     BEGIN CODE
C     ----------
      NTRY=NTRY+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (GOODHEL(IHEL) .OR. NTRY .LT. 100) THEN
          T=MATRIX_PROD(P ,NHEL(1,IHEL),JC(1))
          ANS=ANS+T
          IF (T .NE. 0D0) THEN
            GOODHEL(IHEL)=.TRUE.
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)
      END


      REAL*8 FUNCTION MATRIX_PROD(P,NHEL,IC)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.9.21, 2024-09-26
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: g g > t t~ t t~ WEIGHTED<=4 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=76)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=18, NCOLOR=12)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 TMP_JAMP(0)
      COMPLEX*16 W(18,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'
      DOUBLE PRECISION AMP2(NGRAPHS)
      COMMON/TO_AMPS/  AMP2
C     
C     COLOR DATA
C     
      DATA (CF(I,  1),I=  1,  6) /1.600000000000000D+01
     $ ,5.333333333333333D+00,5.333333333333333D+00,2.000000000000000D
     $ +00,0.000000000000000D+00,5.333333333333333D+00/
      DATA (CF(I,  1),I=  7, 12) /-6.666666666666666D-01
     $ ,0.000000000000000D+00,-2.000000000000000D+00,
     $ -6.666666666666666D-01,-6.666666666666666D-01
     $ ,2.000000000000000D+00/
C     1 T(1,2,3,4) T(5,6)
      DATA (CF(I,  2),I=  1,  6) /5.333333333333333D+00
     $ ,1.600000000000000D+01,2.000000000000000D+00,5.333333333333333D
     $ +00,5.333333333333333D+00,0.000000000000000D+00/
      DATA (CF(I,  2),I=  7, 12) /0.000000000000000D+00,
     $ -6.666666666666666D-01,-6.666666666666666D-01,
     $ -2.000000000000000D+00,2.000000000000000D+00,
     $ -6.666666666666666D-01/
C     1 T(1,2,3,6) T(5,4)
      DATA (CF(I,  3),I=  1,  6) /5.333333333333333D+00
     $ ,2.000000000000000D+00,1.600000000000000D+01,5.333333333333333D
     $ +00,-6.666666666666666D-01,0.000000000000000D+00/
      DATA (CF(I,  3),I=  7, 12) /0.000000000000000D+00
     $ ,5.333333333333333D+00,-6.666666666666666D-01
     $ ,2.000000000000000D+00,-2.000000000000000D+00,
     $ -6.666666666666666D-01/
C     1 T(1,2,5,4) T(3,6)
      DATA (CF(I,  4),I=  1,  6) /2.000000000000000D+00
     $ ,5.333333333333333D+00,5.333333333333333D+00,1.600000000000000D
     $ +01,0.000000000000000D+00,-6.666666666666666D-01/
      DATA (CF(I,  4),I=  7, 12) /5.333333333333333D+00
     $ ,0.000000000000000D+00,2.000000000000000D+00,
     $ -6.666666666666666D-01,-6.666666666666666D-01,
     $ -2.000000000000000D+00/
C     1 T(1,2,5,6) T(3,4)
      DATA (CF(I,  5),I=  1,  6) /0.000000000000000D+00
     $ ,5.333333333333333D+00,-6.666666666666666D-01
     $ ,0.000000000000000D+00,1.600000000000000D+01,5.333333333333333D
     $ +00/
      DATA (CF(I,  5),I=  7, 12) /5.333333333333333D+00
     $ ,2.000000000000000D+00,0.000000000000000D+00,
     $ -6.666666666666666D-01,5.333333333333333D+00,0.000000000000000D
     $ +00/
C     1 T(1,3,4) T(2,5,6)
      DATA (CF(I,  6),I=  1,  6) /5.333333333333333D+00
     $ ,0.000000000000000D+00,0.000000000000000D+00,
     $ -6.666666666666666D-01,5.333333333333333D+00,1.600000000000000D
     $ +01/
      DATA (CF(I,  6),I=  7, 12) /2.000000000000000D+00
     $ ,5.333333333333333D+00,-6.666666666666666D-01
     $ ,0.000000000000000D+00,0.000000000000000D+00,5.333333333333333D
     $ +00/
C     1 T(1,3,6) T(2,5,4)
      DATA (CF(I,  7),I=  1,  6) /-6.666666666666666D-01
     $ ,0.000000000000000D+00,0.000000000000000D+00,5.333333333333333D
     $ +00,5.333333333333333D+00,2.000000000000000D+00/
      DATA (CF(I,  7),I=  7, 12) /1.600000000000000D+01
     $ ,5.333333333333333D+00,5.333333333333333D+00,0.000000000000000D
     $ +00,0.000000000000000D+00,-6.666666666666666D-01/
C     1 T(1,5,4) T(2,3,6)
      DATA (CF(I,  8),I=  1,  6) /0.000000000000000D+00,
     $ -6.666666666666666D-01,5.333333333333333D+00,0.000000000000000D
     $ +00,2.000000000000000D+00,5.333333333333333D+00/
      DATA (CF(I,  8),I=  7, 12) /5.333333333333333D+00
     $ ,1.600000000000000D+01,0.000000000000000D+00,5.333333333333333D
     $ +00,-6.666666666666666D-01,0.000000000000000D+00/
C     1 T(1,5,6) T(2,3,4)
      DATA (CF(I,  9),I=  1,  6) /-2.000000000000000D+00,
     $ -6.666666666666666D-01,-6.666666666666666D-01
     $ ,2.000000000000000D+00,0.000000000000000D+00,
     $ -6.666666666666666D-01/
      DATA (CF(I,  9),I=  7, 12) /5.333333333333333D+00
     $ ,0.000000000000000D+00,1.600000000000000D+01,5.333333333333333D
     $ +00,5.333333333333333D+00,2.000000000000000D+00/
C     1 T(2,1,3,4) T(5,6)
      DATA (CF(I, 10),I=  1,  6) /-6.666666666666666D-01,
     $ -2.000000000000000D+00,2.000000000000000D+00,
     $ -6.666666666666666D-01,-6.666666666666666D-01
     $ ,0.000000000000000D+00/
      DATA (CF(I, 10),I=  7, 12) /0.000000000000000D+00
     $ ,5.333333333333333D+00,5.333333333333333D+00,1.600000000000000D
     $ +01,2.000000000000000D+00,5.333333333333333D+00/
C     1 T(2,1,3,6) T(5,4)
      DATA (CF(I, 11),I=  1,  6) /-6.666666666666666D-01
     $ ,2.000000000000000D+00,-2.000000000000000D+00,
     $ -6.666666666666666D-01,5.333333333333333D+00,0.000000000000000D
     $ +00/
      DATA (CF(I, 11),I=  7, 12) /0.000000000000000D+00,
     $ -6.666666666666666D-01,5.333333333333333D+00,2.000000000000000D
     $ +00,1.600000000000000D+01,5.333333333333333D+00/
C     1 T(2,1,5,4) T(3,6)
      DATA (CF(I, 12),I=  1,  6) /2.000000000000000D+00,
     $ -6.666666666666666D-01,-6.666666666666666D-01,
     $ -2.000000000000000D+00,0.000000000000000D+00,5.333333333333333D
     $ +00/
      DATA (CF(I, 12),I=  7, 12) /-6.666666666666666D-01
     $ ,0.000000000000000D+00,2.000000000000000D+00,5.333333333333333D
     $ +00,5.333333333333333D+00,1.600000000000000D+01/
C     1 T(2,1,5,6) T(3,4)
C     ----------
C     BEGIN CODE
C     ----------
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))
      CALL VXXXXX(P(0,2),ZERO,NHEL(2),-1*IC(2),W(1,2))
      CALL OXXXXX(P(0,3),MDL_MT,NHEL(3),+1*IC(3),W(1,3))
      CALL IXXXXX(P(0,4),MDL_MT,NHEL(4),-1*IC(4),W(1,4))
      CALL OXXXXX(P(0,5),MDL_MT,NHEL(5),+1*IC(5),W(1,5))
      CALL IXXXXX(P(0,6),MDL_MT,NHEL(6),-1*IC(6),W(1,6))
      CALL VVV1P0_1(W(1,1),W(1,2),GC_10,ZERO,ZERO,W(1,7))
      CALL FFV1P0_3(W(1,4),W(1,3),GC_11,ZERO,ZERO,W(1,8))
      CALL FFV1_1(W(1,5),W(1,7),GC_11,MDL_MT,MDL_WT,W(1,9))
C     Amplitude(s) for diagram number 1
      CALL FFV1_0(W(1,6),W(1,9),W(1,8),GC_11,AMP(1))
      CALL FFV1_2(W(1,6),W(1,7),GC_11,MDL_MT,MDL_WT,W(1,10))
C     Amplitude(s) for diagram number 2
      CALL FFV1_0(W(1,10),W(1,5),W(1,8),GC_11,AMP(2))
      CALL FFV1P0_3(W(1,6),W(1,5),GC_11,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 3
      CALL VVV1_0(W(1,7),W(1,8),W(1,11),GC_10,AMP(3))
      CALL FFV1P0_3(W(1,6),W(1,3),GC_11,ZERO,ZERO,W(1,12))
      CALL FFV1_2(W(1,4),W(1,7),GC_11,MDL_MT,MDL_WT,W(1,13))
C     Amplitude(s) for diagram number 4
      CALL FFV1_0(W(1,13),W(1,5),W(1,12),GC_11,AMP(4))
C     Amplitude(s) for diagram number 5
      CALL FFV1_0(W(1,4),W(1,9),W(1,12),GC_11,AMP(5))
      CALL FFV1P0_3(W(1,4),W(1,5),GC_11,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 6
      CALL VVV1_0(W(1,7),W(1,12),W(1,9),GC_10,AMP(6))
      CALL FFV1_1(W(1,3),W(1,7),GC_11,MDL_MT,MDL_WT,W(1,14))
C     Amplitude(s) for diagram number 7
      CALL FFV1_0(W(1,6),W(1,14),W(1,9),GC_11,AMP(7))
C     Amplitude(s) for diagram number 8
      CALL FFV1_0(W(1,10),W(1,3),W(1,9),GC_11,AMP(8))
C     Amplitude(s) for diagram number 9
      CALL FFV1_0(W(1,4),W(1,14),W(1,11),GC_11,AMP(9))
C     Amplitude(s) for diagram number 10
      CALL FFV1_0(W(1,13),W(1,3),W(1,11),GC_11,AMP(10))
      CALL FFV1_1(W(1,3),W(1,1),GC_11,MDL_MT,MDL_WT,W(1,13))
      CALL FFV1_2(W(1,4),W(1,2),GC_11,MDL_MT,MDL_WT,W(1,14))
      CALL FFV1P0_3(W(1,6),W(1,13),GC_11,ZERO,ZERO,W(1,10))
C     Amplitude(s) for diagram number 11
      CALL FFV1_0(W(1,14),W(1,5),W(1,10),GC_11,AMP(11))
C     Amplitude(s) for diagram number 12
      CALL FFV1_0(W(1,14),W(1,13),W(1,11),GC_11,AMP(12))
      CALL FFV1_1(W(1,5),W(1,2),GC_11,MDL_MT,MDL_WT,W(1,7))
      CALL FFV1P0_3(W(1,4),W(1,13),GC_11,ZERO,ZERO,W(1,15))
C     Amplitude(s) for diagram number 13
      CALL FFV1_0(W(1,6),W(1,7),W(1,15),GC_11,AMP(13))
C     Amplitude(s) for diagram number 14
      CALL FFV1_0(W(1,4),W(1,7),W(1,10),GC_11,AMP(14))
      CALL FFV1_2(W(1,6),W(1,2),GC_11,MDL_MT,MDL_WT,W(1,16))
C     Amplitude(s) for diagram number 15
      CALL FFV1_0(W(1,16),W(1,5),W(1,15),GC_11,AMP(15))
C     Amplitude(s) for diagram number 16
      CALL FFV1_0(W(1,16),W(1,13),W(1,9),GC_11,AMP(16))
      CALL FFV1_1(W(1,13),W(1,2),GC_11,MDL_MT,MDL_WT,W(1,17))
C     Amplitude(s) for diagram number 17
      CALL FFV1_0(W(1,6),W(1,17),W(1,9),GC_11,AMP(17))
C     Amplitude(s) for diagram number 18
      CALL VVV1_0(W(1,2),W(1,9),W(1,10),GC_10,AMP(18))
C     Amplitude(s) for diagram number 19
      CALL FFV1_0(W(1,4),W(1,17),W(1,11),GC_11,AMP(19))
C     Amplitude(s) for diagram number 20
      CALL VVV1_0(W(1,2),W(1,11),W(1,15),GC_10,AMP(20))
      CALL FFV1_2(W(1,4),W(1,1),GC_11,MDL_MT,MDL_WT,W(1,15))
      CALL FFV1_1(W(1,3),W(1,2),GC_11,MDL_MT,MDL_WT,W(1,17))
      CALL FFV1P0_3(W(1,15),W(1,5),GC_11,ZERO,ZERO,W(1,10))
C     Amplitude(s) for diagram number 21
      CALL FFV1_0(W(1,6),W(1,17),W(1,10),GC_11,AMP(21))
C     Amplitude(s) for diagram number 22
      CALL FFV1_0(W(1,15),W(1,17),W(1,11),GC_11,AMP(22))
      CALL FFV1P0_3(W(1,15),W(1,3),GC_11,ZERO,ZERO,W(1,13))
C     Amplitude(s) for diagram number 23
      CALL FFV1_0(W(1,6),W(1,7),W(1,13),GC_11,AMP(23))
C     Amplitude(s) for diagram number 24
      CALL FFV1_0(W(1,15),W(1,7),W(1,12),GC_11,AMP(24))
C     Amplitude(s) for diagram number 25
      CALL FFV1_0(W(1,16),W(1,5),W(1,13),GC_11,AMP(25))
C     Amplitude(s) for diagram number 26
      CALL FFV1_0(W(1,16),W(1,3),W(1,10),GC_11,AMP(26))
      CALL FFV1_2(W(1,15),W(1,2),GC_11,MDL_MT,MDL_WT,W(1,18))
C     Amplitude(s) for diagram number 27
      CALL FFV1_0(W(1,18),W(1,5),W(1,12),GC_11,AMP(27))
C     Amplitude(s) for diagram number 28
      CALL VVV1_0(W(1,2),W(1,12),W(1,10),GC_10,AMP(28))
C     Amplitude(s) for diagram number 29
      CALL FFV1_0(W(1,18),W(1,3),W(1,11),GC_11,AMP(29))
C     Amplitude(s) for diagram number 30
      CALL VVV1_0(W(1,2),W(1,11),W(1,13),GC_10,AMP(30))
      CALL FFV1_1(W(1,5),W(1,1),GC_11,MDL_MT,MDL_WT,W(1,13))
      CALL FFV1P0_3(W(1,4),W(1,13),GC_11,ZERO,ZERO,W(1,18))
C     Amplitude(s) for diagram number 31
      CALL FFV1_0(W(1,6),W(1,17),W(1,18),GC_11,AMP(31))
      CALL FFV1P0_3(W(1,6),W(1,13),GC_11,ZERO,ZERO,W(1,10))
C     Amplitude(s) for diagram number 32
      CALL FFV1_0(W(1,4),W(1,17),W(1,10),GC_11,AMP(32))
C     Amplitude(s) for diagram number 33
      CALL FFV1_0(W(1,14),W(1,3),W(1,10),GC_11,AMP(33))
C     Amplitude(s) for diagram number 34
      CALL FFV1_0(W(1,14),W(1,13),W(1,12),GC_11,AMP(34))
C     Amplitude(s) for diagram number 35
      CALL FFV1_0(W(1,16),W(1,3),W(1,18),GC_11,AMP(35))
C     Amplitude(s) for diagram number 36
      CALL FFV1_0(W(1,16),W(1,13),W(1,8),GC_11,AMP(36))
      CALL FFV1_1(W(1,13),W(1,2),GC_11,MDL_MT,MDL_WT,W(1,15))
C     Amplitude(s) for diagram number 37
      CALL FFV1_0(W(1,6),W(1,15),W(1,8),GC_11,AMP(37))
C     Amplitude(s) for diagram number 38
      CALL VVV1_0(W(1,2),W(1,8),W(1,10),GC_10,AMP(38))
C     Amplitude(s) for diagram number 39
      CALL FFV1_0(W(1,4),W(1,15),W(1,12),GC_11,AMP(39))
C     Amplitude(s) for diagram number 40
      CALL VVV1_0(W(1,2),W(1,12),W(1,18),GC_10,AMP(40))
      CALL FFV1_2(W(1,6),W(1,1),GC_11,MDL_MT,MDL_WT,W(1,18))
      CALL FFV1P0_3(W(1,18),W(1,5),GC_11,ZERO,ZERO,W(1,15))
C     Amplitude(s) for diagram number 41
      CALL FFV1_0(W(1,4),W(1,17),W(1,15),GC_11,AMP(41))
C     Amplitude(s) for diagram number 42
      CALL FFV1_0(W(1,18),W(1,17),W(1,9),GC_11,AMP(42))
      CALL FFV1P0_3(W(1,18),W(1,3),GC_11,ZERO,ZERO,W(1,10))
C     Amplitude(s) for diagram number 43
      CALL FFV1_0(W(1,14),W(1,5),W(1,10),GC_11,AMP(43))
C     Amplitude(s) for diagram number 44
      CALL FFV1_0(W(1,14),W(1,3),W(1,15),GC_11,AMP(44))
C     Amplitude(s) for diagram number 45
      CALL FFV1_0(W(1,4),W(1,7),W(1,10),GC_11,AMP(45))
C     Amplitude(s) for diagram number 46
      CALL FFV1_0(W(1,18),W(1,7),W(1,8),GC_11,AMP(46))
      CALL FFV1_2(W(1,18),W(1,2),GC_11,MDL_MT,MDL_WT,W(1,13))
C     Amplitude(s) for diagram number 47
      CALL FFV1_0(W(1,13),W(1,5),W(1,8),GC_11,AMP(47))
C     Amplitude(s) for diagram number 48
      CALL VVV1_0(W(1,2),W(1,8),W(1,15),GC_10,AMP(48))
C     Amplitude(s) for diagram number 49
      CALL FFV1_0(W(1,13),W(1,3),W(1,9),GC_11,AMP(49))
C     Amplitude(s) for diagram number 50
      CALL VVV1_0(W(1,2),W(1,9),W(1,10),GC_10,AMP(50))
      CALL FFV1_1(W(1,17),W(1,1),GC_11,MDL_MT,MDL_WT,W(1,10))
C     Amplitude(s) for diagram number 51
      CALL FFV1_0(W(1,6),W(1,10),W(1,9),GC_11,AMP(51))
      CALL VVV1P0_1(W(1,1),W(1,9),GC_10,ZERO,ZERO,W(1,13))
C     Amplitude(s) for diagram number 52
      CALL FFV1_0(W(1,6),W(1,17),W(1,13),GC_11,AMP(52))
C     Amplitude(s) for diagram number 53
      CALL FFV1_0(W(1,4),W(1,10),W(1,11),GC_11,AMP(53))
      CALL VVV1P0_1(W(1,1),W(1,11),GC_10,ZERO,ZERO,W(1,10))
C     Amplitude(s) for diagram number 54
      CALL FFV1_0(W(1,4),W(1,17),W(1,10),GC_11,AMP(54))
      CALL FFV1_2(W(1,14),W(1,1),GC_11,MDL_MT,MDL_WT,W(1,17))
C     Amplitude(s) for diagram number 55
      CALL FFV1_0(W(1,17),W(1,5),W(1,12),GC_11,AMP(55))
      CALL VVV1P0_1(W(1,1),W(1,12),GC_10,ZERO,ZERO,W(1,15))
C     Amplitude(s) for diagram number 56
      CALL FFV1_0(W(1,14),W(1,5),W(1,15),GC_11,AMP(56))
C     Amplitude(s) for diagram number 57
      CALL FFV1_0(W(1,17),W(1,3),W(1,11),GC_11,AMP(57))
C     Amplitude(s) for diagram number 58
      CALL FFV1_0(W(1,14),W(1,3),W(1,10),GC_11,AMP(58))
      CALL FFV1_1(W(1,7),W(1,1),GC_11,MDL_MT,MDL_WT,W(1,14))
C     Amplitude(s) for diagram number 59
      CALL FFV1_0(W(1,6),W(1,14),W(1,8),GC_11,AMP(59))
      CALL VVV1P0_1(W(1,1),W(1,8),GC_10,ZERO,ZERO,W(1,17))
C     Amplitude(s) for diagram number 60
      CALL FFV1_0(W(1,6),W(1,7),W(1,17),GC_11,AMP(60))
C     Amplitude(s) for diagram number 61
      CALL FFV1_0(W(1,4),W(1,14),W(1,12),GC_11,AMP(61))
C     Amplitude(s) for diagram number 62
      CALL FFV1_0(W(1,4),W(1,7),W(1,15),GC_11,AMP(62))
      CALL FFV1_2(W(1,16),W(1,1),GC_11,MDL_MT,MDL_WT,W(1,7))
C     Amplitude(s) for diagram number 63
      CALL FFV1_0(W(1,7),W(1,5),W(1,8),GC_11,AMP(63))
C     Amplitude(s) for diagram number 64
      CALL FFV1_0(W(1,16),W(1,5),W(1,17),GC_11,AMP(64))
C     Amplitude(s) for diagram number 65
      CALL FFV1_0(W(1,7),W(1,3),W(1,9),GC_11,AMP(65))
C     Amplitude(s) for diagram number 66
      CALL FFV1_0(W(1,16),W(1,3),W(1,13),GC_11,AMP(66))
C     Amplitude(s) for diagram number 67
      CALL VVVV1_0(W(1,1),W(1,2),W(1,8),W(1,11),GC_12,AMP(67))
      CALL VVVV3_0(W(1,1),W(1,2),W(1,8),W(1,11),GC_12,AMP(68))
      CALL VVVV4_0(W(1,1),W(1,2),W(1,8),W(1,11),GC_12,AMP(69))
C     Amplitude(s) for diagram number 68
      CALL VVV1_0(W(1,2),W(1,11),W(1,17),GC_10,AMP(70))
C     Amplitude(s) for diagram number 69
      CALL VVV1_0(W(1,2),W(1,8),W(1,10),GC_10,AMP(71))
C     Amplitude(s) for diagram number 70
      CALL VVVV1_0(W(1,1),W(1,2),W(1,12),W(1,9),GC_12,AMP(72))
      CALL VVVV3_0(W(1,1),W(1,2),W(1,12),W(1,9),GC_12,AMP(73))
      CALL VVVV4_0(W(1,1),W(1,2),W(1,12),W(1,9),GC_12,AMP(74))
C     Amplitude(s) for diagram number 71
      CALL VVV1_0(W(1,2),W(1,9),W(1,15),GC_10,AMP(75))
C     Amplitude(s) for diagram number 72
      CALL VVV1_0(W(1,2),W(1,12),W(1,13),GC_10,AMP(76))
      JAMP(1)=+1D0/2D0*(+IMAG1*AMP(4)-AMP(6)+IMAG1*AMP(7)+1D0/3D0
     $ *IMAG1*AMP(9)+1D0/3D0*IMAG1*AMP(10)-AMP(11)-1D0/3D0*AMP(12)
     $ -AMP(17)+IMAG1*AMP(18)-1D0/3D0*AMP(19)-AMP(55)-IMAG1*AMP(56)
     $ -1D0/3D0*AMP(57)-AMP(72)-AMP(73)-AMP(75))
      JAMP(2)=+1D0/2D0*(-IMAG1*AMP(2)+AMP(3)-1D0/3D0*IMAG1*AMP(7)-1D0
     $ /3D0*IMAG1*AMP(8)-IMAG1*AMP(9)+AMP(15)+1D0/3D0*AMP(16)+1D0/3D0
     $ *AMP(17)+AMP(19)-IMAG1*AMP(20)+AMP(63)+IMAG1*AMP(64)+1D0/3D0
     $ *AMP(65)+AMP(67)+AMP(68)+AMP(70))
      JAMP(3)=+1D0/2D0*(-IMAG1*AMP(1)-AMP(3)-1D0/3D0*IMAG1*AMP(4)-1D0
     $ /3D0*IMAG1*AMP(5)-IMAG1*AMP(10)+AMP(33)+1D0/3D0*AMP(34)+AMP(37)
     $ -IMAG1*AMP(38)+1D0/3D0*AMP(39)+1D0/3D0*AMP(55)+AMP(57)+IMAG1
     $ *AMP(58)-AMP(67)+AMP(69)+AMP(71))
      JAMP(4)=+1D0/2D0*(+1D0/3D0*IMAG1*AMP(1)+1D0/3D0*IMAG1*AMP(2)
     $ +IMAG1*AMP(5)+AMP(6)+IMAG1*AMP(8)-AMP(35)-1D0/3D0*AMP(36)-1D0
     $ /3D0*AMP(37)-AMP(39)+IMAG1*AMP(40)-1D0/3D0*AMP(63)-AMP(65)
     $ -IMAG1*AMP(66)+AMP(72)-AMP(74)-AMP(76))
      JAMP(5)=+1D0/2D0*(-1D0/3D0*AMP(13)-AMP(14)-1D0/3D0*AMP(15)
     $ -AMP(16)-IMAG1*AMP(18)-1D0/3D0*AMP(23)-AMP(24)-1D0/3D0*AMP(25)
     $ -AMP(26)+IMAG1*AMP(28)-IMAG1*AMP(62)+IMAG1*AMP(66)+AMP(73)
     $ +AMP(74)+AMP(75)+AMP(76))
      JAMP(6)=+1D0/2D0*(+1D0/3D0*AMP(11)+AMP(12)+AMP(13)+1D0/3D0
     $ *AMP(14)+IMAG1*AMP(20)+1D0/3D0*AMP(43)+AMP(44)+1D0/3D0*AMP(45)
     $ +AMP(46)-IMAG1*AMP(48)-IMAG1*AMP(58)+IMAG1*AMP(60)-AMP(68)
     $ -AMP(69)-AMP(70)-AMP(71))
      JAMP(7)=+1D0/2D0*(+1D0/3D0*AMP(21)+AMP(22)+AMP(25)+1D0/3D0
     $ *AMP(26)-IMAG1*AMP(30)+1D0/3D0*AMP(31)+AMP(32)+1D0/3D0*AMP(35)
     $ +AMP(36)+IMAG1*AMP(38)+IMAG1*AMP(54)-IMAG1*AMP(64)-AMP(68)
     $ -AMP(69)-AMP(70)-AMP(71))
      JAMP(8)=+1D0/2D0*(-AMP(31)-1D0/3D0*AMP(32)-1D0/3D0*AMP(33)
     $ -AMP(34)-IMAG1*AMP(40)-1D0/3D0*AMP(41)-AMP(42)-AMP(43)-1D0/3D0
     $ *AMP(44)+IMAG1*AMP(50)-IMAG1*AMP(52)+IMAG1*AMP(56)+AMP(73)
     $ +AMP(74)+AMP(75)+AMP(76))
      JAMP(9)=+1D0/2D0*(-IMAG1*AMP(4)+AMP(6)-IMAG1*AMP(7)-1D0/3D0
     $ *IMAG1*AMP(9)-1D0/3D0*IMAG1*AMP(10)-AMP(21)-1D0/3D0*AMP(22)
     $ -AMP(27)-IMAG1*AMP(28)-1D0/3D0*AMP(29)-AMP(51)+IMAG1*AMP(52)
     $ -1D0/3D0*AMP(53)+AMP(72)-AMP(74)-AMP(76))
      JAMP(10)=+1D0/2D0*(+IMAG1*AMP(2)-AMP(3)+1D0/3D0*IMAG1*AMP(7)+1D0
     $ /3D0*IMAG1*AMP(8)+IMAG1*AMP(9)+AMP(41)+1D0/3D0*AMP(42)+AMP(47)
     $ +IMAG1*AMP(48)+1D0/3D0*AMP(49)+1D0/3D0*AMP(51)+AMP(53)-IMAG1
     $ *AMP(54)-AMP(67)+AMP(69)+AMP(71))
      JAMP(11)=+1D0/2D0*(+IMAG1*AMP(1)+AMP(3)+1D0/3D0*IMAG1*AMP(4)+1D0
     $ /3D0*IMAG1*AMP(5)+IMAG1*AMP(10)+AMP(23)+1D0/3D0*AMP(24)+1D0/3D0
     $ *AMP(27)+AMP(29)+IMAG1*AMP(30)+AMP(59)-IMAG1*AMP(60)+1D0/3D0
     $ *AMP(61)+AMP(67)+AMP(68)+AMP(70))
      JAMP(12)=+1D0/2D0*(-1D0/3D0*IMAG1*AMP(1)-1D0/3D0*IMAG1*AMP(2)
     $ -IMAG1*AMP(5)-AMP(6)-IMAG1*AMP(8)-AMP(45)-1D0/3D0*AMP(46)-1D0
     $ /3D0*AMP(47)-AMP(49)-IMAG1*AMP(50)-1D0/3D0*AMP(59)-AMP(61)
     $ +IMAG1*AMP(62)-AMP(72)-AMP(73)-AMP(75))

      MATRIX_PROD = 0.D0
      DO I = 1, NCOLOR
        ZTEMP = (0.D0,0.D0)
        DO J = 1, NCOLOR
          ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
        ENDDO
        MATRIX_PROD = MATRIX_PROD+ZTEMP*DCONJG(JAMP(I))
      ENDDO
      AMP2(1)=AMP2(1)+AMP(1)*DCONJG(AMP(1))
      AMP2(2)=AMP2(2)+AMP(2)*DCONJG(AMP(2))
      AMP2(3)=AMP2(3)+AMP(3)*DCONJG(AMP(3))
      AMP2(4)=AMP2(4)+AMP(4)*DCONJG(AMP(4))
      AMP2(5)=AMP2(5)+AMP(5)*DCONJG(AMP(5))
      AMP2(6)=AMP2(6)+AMP(6)*DCONJG(AMP(6))
      AMP2(7)=AMP2(7)+AMP(7)*DCONJG(AMP(7))
      AMP2(8)=AMP2(8)+AMP(8)*DCONJG(AMP(8))
      AMP2(9)=AMP2(9)+AMP(9)*DCONJG(AMP(9))
      AMP2(10)=AMP2(10)+AMP(10)*DCONJG(AMP(10))
      AMP2(11)=AMP2(11)+AMP(11)*DCONJG(AMP(11))
      AMP2(12)=AMP2(12)+AMP(12)*DCONJG(AMP(12))
      AMP2(13)=AMP2(13)+AMP(13)*DCONJG(AMP(13))
      AMP2(14)=AMP2(14)+AMP(14)*DCONJG(AMP(14))
      AMP2(15)=AMP2(15)+AMP(15)*DCONJG(AMP(15))
      AMP2(16)=AMP2(16)+AMP(16)*DCONJG(AMP(16))
      AMP2(17)=AMP2(17)+AMP(17)*DCONJG(AMP(17))
      AMP2(18)=AMP2(18)+AMP(18)*DCONJG(AMP(18))
      AMP2(19)=AMP2(19)+AMP(19)*DCONJG(AMP(19))
      AMP2(20)=AMP2(20)+AMP(20)*DCONJG(AMP(20))
      AMP2(21)=AMP2(21)+AMP(21)*DCONJG(AMP(21))
      AMP2(22)=AMP2(22)+AMP(22)*DCONJG(AMP(22))
      AMP2(23)=AMP2(23)+AMP(23)*DCONJG(AMP(23))
      AMP2(24)=AMP2(24)+AMP(24)*DCONJG(AMP(24))
      AMP2(25)=AMP2(25)+AMP(25)*DCONJG(AMP(25))
      AMP2(26)=AMP2(26)+AMP(26)*DCONJG(AMP(26))
      AMP2(27)=AMP2(27)+AMP(27)*DCONJG(AMP(27))
      AMP2(28)=AMP2(28)+AMP(28)*DCONJG(AMP(28))
      AMP2(29)=AMP2(29)+AMP(29)*DCONJG(AMP(29))
      AMP2(30)=AMP2(30)+AMP(30)*DCONJG(AMP(30))
      AMP2(31)=AMP2(31)+AMP(31)*DCONJG(AMP(31))
      AMP2(32)=AMP2(32)+AMP(32)*DCONJG(AMP(32))
      AMP2(33)=AMP2(33)+AMP(33)*DCONJG(AMP(33))
      AMP2(34)=AMP2(34)+AMP(34)*DCONJG(AMP(34))
      AMP2(35)=AMP2(35)+AMP(35)*DCONJG(AMP(35))
      AMP2(36)=AMP2(36)+AMP(36)*DCONJG(AMP(36))
      AMP2(37)=AMP2(37)+AMP(37)*DCONJG(AMP(37))
      AMP2(38)=AMP2(38)+AMP(38)*DCONJG(AMP(38))
      AMP2(39)=AMP2(39)+AMP(39)*DCONJG(AMP(39))
      AMP2(40)=AMP2(40)+AMP(40)*DCONJG(AMP(40))
      AMP2(41)=AMP2(41)+AMP(41)*DCONJG(AMP(41))
      AMP2(42)=AMP2(42)+AMP(42)*DCONJG(AMP(42))
      AMP2(43)=AMP2(43)+AMP(43)*DCONJG(AMP(43))
      AMP2(44)=AMP2(44)+AMP(44)*DCONJG(AMP(44))
      AMP2(45)=AMP2(45)+AMP(45)*DCONJG(AMP(45))
      AMP2(46)=AMP2(46)+AMP(46)*DCONJG(AMP(46))
      AMP2(47)=AMP2(47)+AMP(47)*DCONJG(AMP(47))
      AMP2(48)=AMP2(48)+AMP(48)*DCONJG(AMP(48))
      AMP2(49)=AMP2(49)+AMP(49)*DCONJG(AMP(49))
      AMP2(50)=AMP2(50)+AMP(50)*DCONJG(AMP(50))
      AMP2(51)=AMP2(51)+AMP(51)*DCONJG(AMP(51))
      AMP2(52)=AMP2(52)+AMP(52)*DCONJG(AMP(52))
      AMP2(53)=AMP2(53)+AMP(53)*DCONJG(AMP(53))
      AMP2(54)=AMP2(54)+AMP(54)*DCONJG(AMP(54))
      AMP2(55)=AMP2(55)+AMP(55)*DCONJG(AMP(55))
      AMP2(56)=AMP2(56)+AMP(56)*DCONJG(AMP(56))
      AMP2(57)=AMP2(57)+AMP(57)*DCONJG(AMP(57))
      AMP2(58)=AMP2(58)+AMP(58)*DCONJG(AMP(58))
      AMP2(59)=AMP2(59)+AMP(59)*DCONJG(AMP(59))
      AMP2(60)=AMP2(60)+AMP(60)*DCONJG(AMP(60))
      AMP2(61)=AMP2(61)+AMP(61)*DCONJG(AMP(61))
      AMP2(62)=AMP2(62)+AMP(62)*DCONJG(AMP(62))
      AMP2(63)=AMP2(63)+AMP(63)*DCONJG(AMP(63))
      AMP2(64)=AMP2(64)+AMP(64)*DCONJG(AMP(64))
      AMP2(65)=AMP2(65)+AMP(65)*DCONJG(AMP(65))
      AMP2(66)=AMP2(66)+AMP(66)*DCONJG(AMP(66))
      AMP2(68)=AMP2(68)+AMP(70)*DCONJG(AMP(70))
      AMP2(69)=AMP2(69)+AMP(71)*DCONJG(AMP(71))
      AMP2(71)=AMP2(71)+AMP(75)*DCONJG(AMP(75))
      AMP2(72)=AMP2(72)+AMP(76)*DCONJG(AMP(76))
      END

