ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MZ,MDL_MH,MDL_MT,MDL_MW,MDL_MTA,MDL_MB

      COMMON/MASSES/ MDL_MZ,MDL_MH,MDL_MT,MDL_MW,MDL_MTA,MDL_MB


      DOUBLE PRECISION MDL_WW,MDL_WZ,MDL_WT,MDL_WH

      COMMON/WIDTHS/ MDL_WW,MDL_WZ,MDL_WT,MDL_WH


      DOUBLE COMPLEX GC_10, GC_11, GC_12

      COMMON/COUPLINGS/ GC_10, GC_11, GC_12

