      SUBROUTINE SMATRIX_PROD(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.9.21, 2024-09-26
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: u u~ > t t~ t t~ WEIGHTED<=4 @1
C     Process: c c~ > t t~ t t~ WEIGHTED<=4 @1
C     Process: d d~ > t t~ t t~ WEIGHTED<=4 @1
C     Process: s s~ > t t~ t t~ WEIGHTED<=4 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=64)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
      REAL*8 T
      REAL*8 MATRIX_PROD
      INTEGER IHEL,IDEN, I
      INTEGER JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./
      DATA (NHEL(I,   1),I=1,6) / 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,   2),I=1,6) / 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,   3),I=1,6) / 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,   4),I=1,6) / 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,   5),I=1,6) / 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,   6),I=1,6) / 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,   7),I=1,6) / 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,   8),I=1,6) / 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,   9),I=1,6) / 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  10),I=1,6) / 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  11),I=1,6) / 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  12),I=1,6) / 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  13),I=1,6) / 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  14),I=1,6) / 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  15),I=1,6) / 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  16),I=1,6) / 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  17),I=1,6) / 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  18),I=1,6) / 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  19),I=1,6) / 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  20),I=1,6) / 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  21),I=1,6) / 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  22),I=1,6) / 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  23),I=1,6) / 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  24),I=1,6) / 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  25),I=1,6) / 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  26),I=1,6) / 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  27),I=1,6) / 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  28),I=1,6) / 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  29),I=1,6) / 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  30),I=1,6) / 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  31),I=1,6) / 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  32),I=1,6) / 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  33),I=1,6) /-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  34),I=1,6) /-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  35),I=1,6) /-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  36),I=1,6) /-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  37),I=1,6) /-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  38),I=1,6) /-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  39),I=1,6) /-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  40),I=1,6) /-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  41),I=1,6) /-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  42),I=1,6) /-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  43),I=1,6) /-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  44),I=1,6) /-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  45),I=1,6) /-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  46),I=1,6) /-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  47),I=1,6) /-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  48),I=1,6) /-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  49),I=1,6) /-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  50),I=1,6) /-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  51),I=1,6) /-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  52),I=1,6) /-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  53),I=1,6) /-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  54),I=1,6) /-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  55),I=1,6) /-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  56),I=1,6) /-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  57),I=1,6) /-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  58),I=1,6) /-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  59),I=1,6) /-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  60),I=1,6) /-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  61),I=1,6) /-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  62),I=1,6) /-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  63),I=1,6) /-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  64),I=1,6) /-1, 1, 1,-1, 1,-1/
      DATA IDEN/144/
C     ----------
C     BEGIN CODE
C     ----------
      NTRY=NTRY+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (GOODHEL(IHEL) .OR. NTRY .LT. 100) THEN
          T=MATRIX_PROD(P ,NHEL(1,IHEL),JC(1))
          ANS=ANS+T
          IF (T .NE. 0D0) THEN
            GOODHEL(IHEL)=.TRUE.
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)
      END


      REAL*8 FUNCTION MATRIX_PROD(P,NHEL,IC)
C     
C     Generated by MadGraph5_aMC@NLO v. 2.9.21, 2024-09-26
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: u u~ > t t~ t t~ WEIGHTED<=4 @1
C     Process: c c~ > t t~ t t~ WEIGHTED<=4 @1
C     Process: d d~ > t t~ t t~ WEIGHTED<=4 @1
C     Process: s s~ > t t~ t t~ WEIGHTED<=4 @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=14)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=6)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=13, NCOLOR=6)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 TMP_JAMP(0)
      COMPLEX*16 W(18,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'
      DOUBLE PRECISION AMP2(NGRAPHS)
      COMMON/TO_AMPS/  AMP2
C     
C     COLOR DATA
C     
      DATA (CF(I,  1),I=  1,  6) /2.700000000000000D+01
     $ ,9.000000000000000D+00,9.000000000000000D+00,3.000000000000000D
     $ +00,3.000000000000000D+00,9.000000000000000D+00/
C     1 T(2,1) T(3,4) T(5,6)
      DATA (CF(I,  2),I=  1,  6) /9.000000000000000D+00
     $ ,2.700000000000000D+01,3.000000000000000D+00,9.000000000000000D
     $ +00,9.000000000000000D+00,3.000000000000000D+00/
C     1 T(2,1) T(3,6) T(5,4)
      DATA (CF(I,  3),I=  1,  6) /9.000000000000000D+00
     $ ,3.000000000000000D+00,2.700000000000000D+01,9.000000000000000D
     $ +00,9.000000000000000D+00,3.000000000000000D+00/
C     1 T(2,4) T(3,1) T(5,6)
      DATA (CF(I,  4),I=  1,  6) /3.000000000000000D+00
     $ ,9.000000000000000D+00,9.000000000000000D+00,2.700000000000000D
     $ +01,3.000000000000000D+00,9.000000000000000D+00/
C     1 T(2,4) T(3,6) T(5,1)
      DATA (CF(I,  5),I=  1,  6) /3.000000000000000D+00
     $ ,9.000000000000000D+00,9.000000000000000D+00,3.000000000000000D
     $ +00,2.700000000000000D+01,9.000000000000000D+00/
C     1 T(2,6) T(3,1) T(5,4)
      DATA (CF(I,  6),I=  1,  6) /9.000000000000000D+00
     $ ,3.000000000000000D+00,3.000000000000000D+00,9.000000000000000D
     $ +00,9.000000000000000D+00,2.700000000000000D+01/
C     1 T(2,6) T(3,4) T(5,1)
C     ----------
C     BEGIN CODE
C     ----------
      CALL IXXXXX(P(0,1),ZERO,NHEL(1),+1*IC(1),W(1,1))
      CALL OXXXXX(P(0,2),ZERO,NHEL(2),-1*IC(2),W(1,2))
      CALL OXXXXX(P(0,3),MDL_MT,NHEL(3),+1*IC(3),W(1,3))
      CALL IXXXXX(P(0,4),MDL_MT,NHEL(4),-1*IC(4),W(1,4))
      CALL OXXXXX(P(0,5),MDL_MT,NHEL(5),+1*IC(5),W(1,5))
      CALL IXXXXX(P(0,6),MDL_MT,NHEL(6),-1*IC(6),W(1,6))
      CALL FFV1P0_3(W(1,1),W(1,2),GC_11,ZERO,ZERO,W(1,7))
      CALL FFV1P0_3(W(1,4),W(1,3),GC_11,ZERO,ZERO,W(1,8))
      CALL FFV1_1(W(1,5),W(1,7),GC_11,MDL_MT,MDL_WT,W(1,9))
C     Amplitude(s) for diagram number 1
      CALL FFV1_0(W(1,6),W(1,9),W(1,8),GC_11,AMP(1))
      CALL FFV1_2(W(1,6),W(1,7),GC_11,MDL_MT,MDL_WT,W(1,10))
C     Amplitude(s) for diagram number 2
      CALL FFV1_0(W(1,10),W(1,5),W(1,8),GC_11,AMP(2))
      CALL FFV1P0_3(W(1,6),W(1,5),GC_11,ZERO,ZERO,W(1,11))
C     Amplitude(s) for diagram number 3
      CALL VVV1_0(W(1,7),W(1,8),W(1,11),GC_10,AMP(3))
      CALL FFV1P0_3(W(1,6),W(1,3),GC_11,ZERO,ZERO,W(1,12))
      CALL FFV1_2(W(1,4),W(1,7),GC_11,MDL_MT,MDL_WT,W(1,13))
C     Amplitude(s) for diagram number 4
      CALL FFV1_0(W(1,13),W(1,5),W(1,12),GC_11,AMP(4))
C     Amplitude(s) for diagram number 5
      CALL FFV1_0(W(1,4),W(1,9),W(1,12),GC_11,AMP(5))
      CALL FFV1P0_3(W(1,4),W(1,5),GC_11,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 6
      CALL VVV1_0(W(1,7),W(1,12),W(1,9),GC_10,AMP(6))
      CALL FFV1_1(W(1,3),W(1,7),GC_11,MDL_MT,MDL_WT,W(1,5))
C     Amplitude(s) for diagram number 7
      CALL FFV1_0(W(1,6),W(1,5),W(1,9),GC_11,AMP(7))
C     Amplitude(s) for diagram number 8
      CALL FFV1_0(W(1,10),W(1,3),W(1,9),GC_11,AMP(8))
C     Amplitude(s) for diagram number 9
      CALL FFV1_0(W(1,4),W(1,5),W(1,11),GC_11,AMP(9))
C     Amplitude(s) for diagram number 10
      CALL FFV1_0(W(1,13),W(1,3),W(1,11),GC_11,AMP(10))
      CALL FFV1_2(W(1,1),W(1,8),GC_11,ZERO,ZERO,W(1,13))
C     Amplitude(s) for diagram number 11
      CALL FFV1_0(W(1,13),W(1,2),W(1,11),GC_11,AMP(11))
      CALL FFV1_2(W(1,1),W(1,11),GC_11,ZERO,ZERO,W(1,13))
C     Amplitude(s) for diagram number 12
      CALL FFV1_0(W(1,13),W(1,2),W(1,8),GC_11,AMP(12))
      CALL FFV1_2(W(1,1),W(1,12),GC_11,ZERO,ZERO,W(1,13))
C     Amplitude(s) for diagram number 13
      CALL FFV1_0(W(1,13),W(1,2),W(1,9),GC_11,AMP(13))
      CALL FFV1_2(W(1,1),W(1,9),GC_11,ZERO,ZERO,W(1,13))
C     Amplitude(s) for diagram number 14
      CALL FFV1_0(W(1,13),W(1,2),W(1,12),GC_11,AMP(14))
      JAMP(1)=+1D0/4D0*(+1D0/9D0*AMP(1)+1D0/9D0*AMP(2)+1D0/3D0*AMP(4)
     $ +1D0/3D0*AMP(5)+1D0/3D0*AMP(7)+1D0/3D0*AMP(8)+1D0/9D0*AMP(9)
     $ +1D0/9D0*AMP(10)+1D0/9D0*AMP(11)+1D0/9D0*AMP(12))
      JAMP(2)=+1D0/4D0*(-1D0/3D0*AMP(1)-1D0/3D0*AMP(2)-1D0/9D0*AMP(4)
     $ -1D0/9D0*AMP(5)-1D0/9D0*AMP(7)-1D0/9D0*AMP(8)-1D0/3D0*AMP(9)
     $ -1D0/3D0*AMP(10)-1D0/9D0*AMP(13)-1D0/9D0*AMP(14))
      JAMP(3)=+1D0/4D0*(-AMP(4)-IMAG1*AMP(6)-AMP(7)-1D0/3D0*AMP(9)-1D0
     $ /3D0*AMP(10)-1D0/3D0*AMP(11)-1D0/3D0*AMP(12)-AMP(13))
      JAMP(4)=+1D0/4D0*(+AMP(1)-IMAG1*AMP(3)+1D0/3D0*AMP(4)+1D0/3D0
     $ *AMP(5)+AMP(10)+AMP(12)+1D0/3D0*AMP(13)+1D0/3D0*AMP(14))
      JAMP(5)=+1D0/4D0*(+AMP(2)+IMAG1*AMP(3)+1D0/3D0*AMP(7)+1D0/3D0
     $ *AMP(8)+AMP(9)+AMP(11)+1D0/3D0*AMP(13)+1D0/3D0*AMP(14))
      JAMP(6)=+1D0/4D0*(-1D0/3D0*AMP(1)-1D0/3D0*AMP(2)-AMP(5)+IMAG1
     $ *AMP(6)-AMP(8)-1D0/3D0*AMP(11)-1D0/3D0*AMP(12)-AMP(14))

      MATRIX_PROD = 0.D0
      DO I = 1, NCOLOR
        ZTEMP = (0.D0,0.D0)
        DO J = 1, NCOLOR
          ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
        ENDDO
        MATRIX_PROD = MATRIX_PROD+ZTEMP*DCONJG(JAMP(I))
      ENDDO
      AMP2(1)=AMP2(1)+AMP(1)*DCONJG(AMP(1))
      AMP2(2)=AMP2(2)+AMP(2)*DCONJG(AMP(2))
      AMP2(3)=AMP2(3)+AMP(3)*DCONJG(AMP(3))
      AMP2(4)=AMP2(4)+AMP(4)*DCONJG(AMP(4))
      AMP2(5)=AMP2(5)+AMP(5)*DCONJG(AMP(5))
      AMP2(6)=AMP2(6)+AMP(6)*DCONJG(AMP(6))
      AMP2(7)=AMP2(7)+AMP(7)*DCONJG(AMP(7))
      AMP2(8)=AMP2(8)+AMP(8)*DCONJG(AMP(8))
      AMP2(9)=AMP2(9)+AMP(9)*DCONJG(AMP(9))
      AMP2(10)=AMP2(10)+AMP(10)*DCONJG(AMP(10))
      AMP2(11)=AMP2(11)+AMP(11)*DCONJG(AMP(11))
      AMP2(12)=AMP2(12)+AMP(12)*DCONJG(AMP(12))
      AMP2(13)=AMP2(13)+AMP(13)*DCONJG(AMP(13))
      AMP2(14)=AMP2(14)+AMP(14)*DCONJG(AMP(14))
      END

